version: 0.0
os: linux
files:
  - source: ./
    destination: /usr/local/bin
permissions:
  - object: /
     pattern: "**"
     owner: ec2-user
     group: ec2-user
hooks:
  AfterInstall:
     - location: codedeploy-install
       timeout: 5
       runas: ec2-user
  ApplicationStop:
     - location: codedeploy-stop
       timeout: 5
       runas: ec2-user
  ApplicationStart:
     - location: codedeploy-start
       timeout: 5
       runas: ec2-user